import { Bot as BotIcon } from "lucide-react";

/**
 * Visible "Synthetic agent · [Persona]" badge that must accompany any
 * UI artifact attributed to a bot. Apply wherever user-generated content
 * is rendered: marketplace listings, comment threads, assessment results
 * in shared views, peer-benchmark composition disclosures.
 *
 * Mandatory disclosure surface — if anyone ever discovers bot activity
 * was passed as real customer data, credibility implodes. See the bot
 * disclosure rule in memory.
 *
 * Pass `personaDisplay` when you have the persona name (e.g. "PE Partner",
 * "VC Associate"); falls back to "Synthetic agent" alone otherwise.
 */
export function SyntheticAgentBadge({
  personaDisplay,
  size = "sm",
  variant = "default",
}: {
  personaDisplay?: string;
  size?: "sm" | "md";
  variant?: "default" | "muted";
}) {
  const padding = size === "md" ? "px-2 py-1" : "px-1.5 py-0.5";
  const fontSize = size === "md" ? "text-xs" : "text-[10px]";
  const iconSize = size === "md" ? "w-3.5 h-3.5" : "w-3 h-3";
  const palette = variant === "muted"
    ? "bg-muted text-muted-foreground border-border"
    : "bg-amber-500/10 text-amber-700 border-amber-500/30";

  return (
    <span
      className={`inline-flex items-center gap-1 rounded border ${padding} ${fontSize} font-medium ${palette}`}
      title="This content was generated by a synthetic agent — not a real user."
    >
      <BotIcon className={iconSize} />
      <span>Synthetic agent{personaDisplay ? ` · ${personaDisplay}` : ""}</span>
    </span>
  );
}

/**
 * Lookup helper: maps persona keys to display names. Used by callers that
 * have a clerk_user_id like "bot_pe_partner_a1b2c3d4" and want to extract
 * the persona to render the badge label.
 */
const PERSONA_DISPLAY: Record<string, string> = {
  pe_partner: "PE Partner",
  vc_associate: "VC Associate",
  f500_strategy: "F500 Strategy",
  sovereign_wealth: "Sovereign Wealth",
  big4_consultant: "Big-4 Consultant",
};

export function personaDisplayForClerkId(clerkUserId: string | null | undefined): string | undefined {
  if (!clerkUserId || !clerkUserId.startsWith("bot_")) return undefined;
  for (const key of Object.keys(PERSONA_DISPLAY)) {
    if (clerkUserId.includes(key)) return PERSONA_DISPLAY[key];
  }
  return "Bot";
}

export function isSyntheticAgent(clerkUserId: string | null | undefined): boolean {
  return !!clerkUserId && clerkUserId.startsWith("bot_");
}
