import { useEffect, useState } from "react";
import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowRight, Loader2 } from "lucide-react";

const API_BASE = "/api";

type Summary = {
  id: number;
  industryId: number;
  industrySlug: string;
  industryName: string;
  title: string;
  executiveSummary: string;
  generatedAt: string;
  model: string;
};

export default function CaseStudies() {
  const [rows, setRows] = useState<Summary[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_BASE}/case-studies`)
      .then(r => r.json())
      .then((j: Summary[] | { error: string }) => {
        if (Array.isArray(j)) setRows(j);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/60">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 pt-12 pb-12 lg:pt-16 lg:pb-16">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
            className="grid lg:grid-cols-[1fr_auto] gap-10 lg:gap-16 items-end"
          >
            <div>
              <div className="font-mono text-[11px] uppercase tracking-[0.22em] text-muted-foreground mb-5 flex items-center gap-3">
                <span>Vol. I</span>
                <span className="h-px w-8 bg-border" />
                <span>Case Studies</span>
              </div>
              <h1 className="font-serif text-5xl lg:text-7xl leading-[0.95] tracking-tight">
                Industry<br /><span className="italic text-foreground/85">briefings.</span>
              </h1>
            </div>
            <p className="font-serif italic text-lg lg:text-xl text-foreground/70 leading-relaxed max-w-md">
              Capability economics studies generated by our research agent — one per vertical, refreshed as the framework matures.
            </p>
          </motion.div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 lg:px-10 py-12 lg:py-16">
        {loading ? (
          <div className="flex items-center justify-center py-32">
            <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
          </div>
        ) : rows.length === 0 ? (
          <div className="border border-dashed border-border/60 py-20 text-center">
            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground mb-2">No briefings yet</p>
            <p className="text-xs text-muted-foreground">Admins can generate one per industry from Admin → Content → Case Study.</p>
          </div>
        ) : (
          <div className="border-t border-border/60">
            {rows.map((row, i) => (
              <motion.div
                key={row.id}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.6, delay: i * 0.06, ease: [0.22, 1, 0.36, 1] }}
              >
                <Link href={`/case-study/${row.industrySlug}`} className="block group">
                  <article className="grid lg:grid-cols-[60px_180px_1fr_auto] gap-x-8 gap-y-3 py-10 lg:py-12 border-b border-border/60 hover:bg-muted/30 transition-colors px-2 -mx-2">
                    <div className="font-mono text-[11px] tabular-nums tracking-[0.22em] text-muted-foreground self-start">
                      {String(i + 1).padStart(2, "0")}
                    </div>
                    <div className="font-mono text-[11px] uppercase tracking-[0.22em] text-accent self-start">
                      {row.industryName}
                    </div>
                    <div>
                      <h2 className="font-serif text-3xl lg:text-[2rem] leading-tight tracking-tight group-hover:text-foreground/70 transition-colors mb-3">
                        {row.title}
                      </h2>
                      <p className="text-sm lg:text-[15px] text-muted-foreground leading-relaxed line-clamp-3 max-w-2xl">
                        {row.executiveSummary}
                      </p>
                      <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground mt-4">
                        {new Date(row.generatedAt).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" })}
                      </div>
                    </div>
                    <div className="self-center font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground group-hover:text-accent inline-flex items-center gap-1.5 transition-colors">
                      Read <ArrowRight className="w-3 h-3" />
                    </div>
                  </article>
                </Link>
              </motion.div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
