import { useEffect, useState } from "react";
import { Link } from "wouter";
import { BookOpen, Loader2 } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

const API_BASE = "/api";

type Summary = {
  id: number;
  industryId: number;
  industrySlug: string;
  industryName: string;
  title: string;
  executiveSummary: string;
  generatedAt: string;
  model: string;
};

export default function CaseStudies() {
  const [rows, setRows] = useState<Summary[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_BASE}/case-studies`)
      .then(r => r.json())
      .then((j: Summary[] | { error: string }) => {
        if (Array.isArray(j)) setRows(j);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="container mx-auto px-4 py-12 max-w-5xl">
      <div className="mb-10">
        <h1 className="font-serif text-4xl flex items-center gap-3 mb-2">
          <BookOpen className="w-8 h-8 text-primary" />
          Case studies
        </h1>
        <p className="text-muted-foreground text-lg">
          Industry-specific capability economics studies generated by our research agent.
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>
      ) : rows.length === 0 ? (
        <Card className="rounded-none">
          <CardContent className="p-12 text-center text-sm text-muted-foreground">
            <p>No case studies have been generated yet.</p>
            <p className="text-xs mt-2">Admins can generate one per industry from Admin → Content → Case Study.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {rows.map(row => (
            <Link key={row.id} href={`/case-study/${row.industrySlug}`}>
              <Card className="rounded-none cursor-pointer hover:border-primary transition-colors h-full">
                <CardContent className="p-6 flex flex-col h-full">
                  <div className="text-xs uppercase tracking-wider text-muted-foreground mb-2">
                    {row.industryName}
                  </div>
                  <h2 className="font-serif text-xl mb-3">{row.title}</h2>
                  <p className="text-sm text-muted-foreground line-clamp-4 flex-1">{row.executiveSummary}</p>
                  <div className="mt-4 pt-3 border-t text-xs text-muted-foreground">
                    {new Date(row.generatedAt).toLocaleDateString()}
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
