import { Router, type IRouter } from "express";
import healthRouter from "./health";
import industriesRouter from "./industries";
import capabilitiesRouter from "./capabilities";
import organizationsRouter from "./organizations";
import dashboardRouter from "./dashboard";
import projectsRouter from "./projects";
import insightsRouter from "./insights";
import ceiRouter from "./cei";
import agentRouter from "./agent";
import contentRouter from "./content";
import assessRouter from "./assess";
import secRouter from "./sec";
import adminRouter from "./admin";
import enrichmentRouter from "./enrichment";
import { enrichmentAliasRouter } from "./enrichment";
import educationalContentRouter from "./educational-content";
import caseStudiesRouter from "./case-studies";
import dynamicIndustriesRouter from "./dynamic-industries";
import vceRouter from "./vce";
import alphaRouter from "./alpha";
import reviewRouter from "./review";
import membershipRouter from "./membership";
import macroEventsRouter from "./macro-events";
import companiesRouter from "./companies";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dynamicIndustriesRouter);
router.use(industriesRouter);
router.use(enrichmentAliasRouter);
router.use(capabilitiesRouter);
router.use(organizationsRouter);
router.use(dashboardRouter);
router.use(projectsRouter);
router.use(insightsRouter);
router.use(ceiRouter);
router.use(agentRouter);
router.use(contentRouter);
router.use(assessRouter);
router.use(secRouter);
router.use(adminRouter);
router.use(educationalContentRouter);
router.use(caseStudiesRouter);
router.use(vceRouter);
router.use("/enrichment", enrichmentRouter);
router.use("/alpha", alphaRouter);
router.use(reviewRouter);
router.use(membershipRouter);
router.use(macroEventsRouter);
router.use(companiesRouter);

export default router;
