/**
 * Client-side export helpers.
 *
 * Move 3 of the strategic UX overhaul: every analytical page needs to
 * produce an artifact the visitor can actually take with them. PE leaves
 * with an IC memo, VC leaves with a thesis note, F500 leaves with a
 * board-ready CSV, students/professors leave with a dataset.
 *
 * This module is the lowest-level layer: pure functions for turning
 * structured data into CSV / Markdown strings and triggering a browser
 * download. UI lives in components/export-menu.tsx; the AI narrative
 * wrapper is fetched from POST /api/exports/narrative (routes/exports.ts
 * on the server).
 *
 * Why client-side: no server round-trip cost, no PII leaves the user's
 * machine, instant download. We only call the server when the user opts
 * into the AI-written narrative wrapper.
 */

export interface ExportRow {
  [key: string]: string | number | boolean | null | undefined;
}

/**
 * Convert an array of homogeneous rows to a CSV string. Column order is
 * taken from the union of all row keys, so heterogeneous rows merge
 * sensibly. Cells with commas/quotes/newlines are RFC4180-escaped.
 */
export function toCSV(rows: ExportRow[]): string {
  if (rows.length === 0) return "";
  const headers = Array.from(new Set(rows.flatMap(r => Object.keys(r))));
  const escape = (v: string | number | boolean | null | undefined): string => {
    if (v === null || v === undefined) return "";
    const s = String(v);
    if (s.includes(",") || s.includes('"') || s.includes("\n")) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };
  const lines = [headers.join(",")];
  for (const row of rows) {
    lines.push(headers.map(h => escape(row[h])).join(","));
  }
  return lines.join("\n");
}

/**
 * Turn page data into Notion-flavored Markdown. We keep the dialect plain
 * enough that GitHub / Notion / Obsidian / Slack all render it cleanly.
 */
export interface MarkdownSection {
  heading: string;
  /** Optional paragraph body. */
  body?: string;
  /** Optional table — first row is headers, rest are data rows. */
  table?: Array<Array<string | number>>;
  /** Optional bullet list. */
  bullets?: string[];
}

export interface MarkdownDocument {
  title: string;
  /** Persona-aware opening narrative (typically AI-generated). */
  narrative?: string;
  /** Subtitle / kicker shown below the title. */
  subtitle?: string;
  /** Inline source URLs that should appear in the footer. */
  sources?: Array<{ url: string; title: string }>;
  sections: MarkdownSection[];
}

function tableToMarkdown(rows: Array<Array<string | number>>): string {
  if (rows.length === 0) return "";
  const headers = rows[0]!.map(String);
  const separator = headers.map(() => "---");
  const body = rows.slice(1).map(r => r.map(c => String(c).replace(/\|/g, "\\|")));
  return [
    `| ${headers.join(" | ")} |`,
    `| ${separator.join(" | ")} |`,
    ...body.map(r => `| ${r.join(" | ")} |`),
  ].join("\n");
}

export function toMarkdown(doc: MarkdownDocument): string {
  const out: string[] = [];
  out.push(`# ${doc.title}`);
  if (doc.subtitle) out.push(`> ${doc.subtitle}`);
  if (doc.narrative) {
    out.push("");
    out.push(doc.narrative);
  }
  for (const s of doc.sections) {
    out.push("");
    out.push(`## ${s.heading}`);
    if (s.body) {
      out.push("");
      out.push(s.body);
    }
    if (s.bullets && s.bullets.length > 0) {
      out.push("");
      for (const b of s.bullets) out.push(`- ${b}`);
    }
    if (s.table && s.table.length > 0) {
      out.push("");
      out.push(tableToMarkdown(s.table));
    }
  }
  if (doc.sources && doc.sources.length > 0) {
    out.push("");
    out.push("---");
    out.push("### Sources");
    for (const src of doc.sources) {
      out.push(`- [${src.title}](${src.url})`);
    }
  }
  out.push("");
  out.push(`*Generated by Capability Economics on ${new Date().toISOString().slice(0, 10)}.*`);
  return out.join("\n");
}

/**
 * Trigger a browser file download. Works in every modern browser by
 * dropping a temporary <a download> element onto the DOM, clicking it,
 * and removing it.
 *
 * Pass a Blob (preferred — we already construct one) or a string (we
 * wrap it as text/plain).
 */
export function downloadFile(filename: string, content: Blob | string, mimeType = "text/plain"): void {
  const blob = typeof content === "string"
    ? new Blob([content], { type: mimeType })
    : content;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 0);
}

/**
 * Fetch an AI-written narrative wrapper from the server. Used by the
 * Export menu's "with AI narrative" option. The server side knows the
 * user's persona and writes the lead paragraph that goes on top of the
 * raw data.
 *
 * Returns null on any failure so callers can graceful-degrade to the
 * non-narrative export.
 */
export async function fetchExportNarrative(args: {
  pageTitle: string;
  /** Short prose describing what the user is exporting (e.g. "Top 25 movers in Healthcare"). */
  summary: string;
  /** Persona key from lib/persona.ts. Server resolves null to "default". */
  persona: string | null;
  /** Up to ~25 representative rows of the data being exported, JSON-stringified. */
  dataSample?: unknown;
}): Promise<string | null> {
  try {
    const resp = await fetch("/api/exports/narrative", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(args),
    });
    if (!resp.ok) return null;
    const data = (await resp.json()) as { narrative?: string };
    return typeof data.narrative === "string" && data.narrative.length > 0 ? data.narrative : null;
  } catch {
    return null;
  }
}
