kind = "web"
previewPath = "/"
title = "Inflexcvi"
version = "1.0.0"
id = "artifacts/inflexcvi"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20020

[services.development]
run = "pnpm --filter @workspace/inflexcvi run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/inflexcvi", "run", "build" ]
publicDir = "artifacts/inflexcvi/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20020"
BASE_PATH = "/"
