import { pgTable, serial, integer, text, timestamp, uniqueIndex, index } from "drizzle-orm/pg-core";

/**
 * Persona-specific recommendations generated by the DVX recommendation
 * engine. For each (capability, persona), the c-suite translator produces
 * a 1-paragraph framing of "what does the DVX score + top disruptors mean
 * for THIS persona's decision-making."
 *
 * Personas: "cfo" | "coo" | "cto" | "chro" | "ceo". Reuses the
 * c_suite_roles table conceptually but doesn't FK to it — personas here
 * are a fixed enum, not user-editable.
 *
 * Generation cost: ~$0.03 per (cap, persona) row. Nightly cron regenerates
 * top-50 highest-DVX capabilities' recs. Lower-priority caps regenerate
 * on-demand when a user hits the API.
 */
export const csuiteRecommendationsTable = pgTable(
  "csuite_recommendations",
  {
    id: serial("id").primaryKey(),
    capabilityId: integer("capability_id").notNull(),
    /** "cfo" | "coo" | "cto" | "chro" | "ceo". */
    personaSlug: text("persona_slug").notNull(),
    /** 1-paragraph recommendation in the persona's voice. */
    body: text("body").notNull(),
    /** One-line action verb extracted from the body for header rendering. */
    headline: text("headline"),
    /** Cached DVX score at generation time so we know when to regenerate. */
    dvxScoreAtGeneration: integer("dvx_score_at_generation"),
    generatedAt: timestamp("generated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("csuite_recs_cap_persona_unique").on(table.capabilityId, table.personaSlug),
    index("csuite_recs_cap_idx").on(table.capabilityId),
  ],
);

export type CsuiteRecommendation = typeof csuiteRecommendationsTable.$inferSelect;
