import { pgTable, serial, integer, real, text, timestamp, jsonb, uniqueIndex, index } from "drizzle-orm/pg-core";
import { capabilitiesTable } from "./capabilities";
import { industriesTable } from "./industries";

/**
 * DVX = Disruption Velocity Index.
 * Tagline: "How fast a capability will be displaced and by what."
 *
 * Runs in parallel with CVI on the same 8h cycle. CVI tells you the
 * current value of a capability; DVX tells you the probability + timing
 * of its extinction.
 *
 * Score is 0-100 (probability %, conceptually). Combined from three
 * weighted factors:
 *   - Velocity Divergence (40%): how much faster a substitute/competing
 *     capability is rising vs this one
 *   - Dependency Fragility (30%): whether upstream deps are being bypassed
 *   - Pattern Match Confidence (30%): Bayesian match against the
 *     disruption_patterns library (Uber/Airbnb/SpaceX/Stripe/Tesla/...)
 *
 * months_to_displacement is a coarse heuristic on top of the score:
 *   >= 80 → 12mo
 *   50-79 → 24mo
 *   30-49 → 36mo
 *   < 30  → null
 *
 * top_disruptors is 2-5 emerging innovations the agent identifies as
 * potential replacers, generated by services/agent/tools.ts:
 * generateDisruptorsTool during the research cycle.
 */
export const dvxComponentsTable = pgTable(
  "dvx_components",
  {
    id: serial("id").primaryKey(),
    capabilityId: integer("capability_id").notNull().references(() => capabilitiesTable.id),
    industryId: integer("industry_id").notNull().references(() => industriesTable.id),
    /** 0-100 disruption probability over a 36-month horizon. */
    disruptionScore: real("disruption_score").notNull(),
    /** EMA-smoothed velocity of disruption_score itself — is the risk
     *  accelerating? Positive = getting worse, negative = retreating. */
    velocity: real("velocity").notNull().default(0),
    monthsToDisplacement: integer("months_to_displacement"),
    /** 2-5 named innovations the agent flagged as potential replacers. */
    topDisruptors: jsonb("top_disruptors").$type<string[]>().notNull().default([]),
    /** FK by slug to disruption_patterns.slug (e.g. "uber", "airbnb"). */
    matchedPatternSlug: text("matched_pattern_slug"),
    /** Per-factor breakdown so the UI can show "what's driving the score". */
    factorBreakdown: jsonb("factor_breakdown").$type<{
      velocityDivergence: number;
      dependencyFragility: number;
      patternMatchConfidence: number;
    }>(),
    /** Free-form rationale from the agent for the score. */
    rationale: text("rationale"),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("dvx_components_cap_industry_idx").on(table.capabilityId, table.industryId),
  ],
);

/**
 * Global + per-industry DVX rollup. One row per 8h cycle, parallel to
 * cvi_snapshots. Used for time-series sparklines of "how disrupted is
 * this industry over time."
 */
export const dvxSnapshotsTable = pgTable("dvx_snapshots", {
  id: serial("id").primaryKey(),
  /** GDP-weighted average of industry-level DVX. 0-100. */
  overallIndex: real("overall_index").notNull(),
  industryBreakdowns: jsonb("industry_breakdowns").$type<Record<string, {
    industryName: string;
    indexValue: number;
    velocity: number;
    weight: number;
    topDisruptedCapability: string;
    topDisruptorInnovation: string;
    capabilityCount: number;
  }>>().notNull(),
  methodologyVersion: text("methodology_version").notNull().default("1.0"),
  snapshotAt: timestamp("snapshot_at").defaultNow().notNull(),
});

/**
 * Per-capability DVX history — mirrors cvi_capability_history. Time-series
 * for the DVX sparkline on the capability detail page. One row per
 * (capability, industry, snapshot_at).
 */
export const dvxCapabilityHistoryTable = pgTable(
  "dvx_capability_history",
  {
    id: serial("id").primaryKey(),
    capabilityId: integer("capability_id").notNull(),
    industryId: integer("industry_id").notNull(),
    disruptionScore: real("disruption_score").notNull(),
    velocity: real("velocity").notNull().default(0),
    monthsToDisplacement: integer("months_to_displacement"),
    matchedPatternSlug: text("matched_pattern_slug"),
    methodologyVersion: text("methodology_version").notNull().default("1.0"),
    snapshotAt: timestamp("snapshot_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("dvx_cap_history_cap_ind_at_unique").on(table.capabilityId, table.industryId, table.snapshotAt),
    index("dvx_cap_history_cap_idx").on(table.capabilityId),
    index("dvx_cap_history_snapshot_at_idx").on(table.snapshotAt),
  ],
);

export type DvxComponent = typeof dvxComponentsTable.$inferSelect;
export type DvxSnapshot = typeof dvxSnapshotsTable.$inferSelect;
export type DvxCapabilityHistory = typeof dvxCapabilityHistoryTable.$inferSelect;
